### ISSUE TITLE
FML Error : Parsing error loading recipe bibliocraft:markerpole

### ISSUE THREAD

**Issue by Thanatosus** [Nuchaz/BiblioCraft#569]
Hello,

I have that kind of error in the terminal:

[FML]: Parsing error loading recipe bibliocraft:markerpole
com.google.gson.JsonSyntaxException: Invalid pattern: empty pattern not allowed
(I put the full error stack in the txt.)

[bibliocraft error stack.txt](https://github.com/Nuchaz/BiblioCraft/files/2042725/bibliocraft.error.stack.txt)

It's not interrupting the loading of server but is quiet strange.

I'm using :
Forge : forge-1.12.2-14.23.4.2703
Sponge : spongeforge-1.12.2-2703-7.1.0-BETA-3119
BiblioCraft : bibliocraft v2.4.4 mc1.12.2

Is that a normal behaviour for the plug-in ? Could there be a conflict with the Forge on the long-term ?

Thank you for your work on BiblioCraft
Have a good day
Thanatosus

**Comment by Nuchaz** [comment]
This is a known issue I haven't resolved yet. It is becasue I have an empty recipe for that item. It is something I don't actually want a recipe for, but in the past, JEI would crash the game if somone tried to click a BiblioCraft block without a recipe. I would bet there is a chance that has been fixed by now, I should really try removing the blank recipes and see if it crashes. I think it may have even been a previous version of Minecraft when that problem existed and I added those.

**Comment by gangraine** [comment]
you need to turn in true in facade.cfg

**Comment by Trackhe** [comment]
push

**Comment by Petschko** [comment]
If it crashes the game it should be resolved, especially if its a know issue for so long. 

(Well it doesnt do it, but still problematic if a player clicks on that item in JEI)

**Comment by lowkeypriority** [comment]
Any update on this?

**Comment by Ironic8b498** [comment]
I was running jei_1.12.2-4.16.1.302 I updated to jei_1.12.2-4.16.1.1001 in my client, and a server reboot, it seems to have fixed the issue

**Comment by ViktorShield** [comment]
Still a problem, doesn't crash though. Had to add the recipe in on my own

**Comment by DiegoF001** [comment]
> Still a problem, doesn't crash though. Had to add the recipe in on my own

what was the recipe that you added?
