### ISSUE TITLE
[1.12.2] "Reading" enchantment not applicable to anything

### ISSUE THREAD

**Issue by praecipitator** [Nuchaz/BiblioCraft#583]
I have several books with "Reading" on them. I have tried applying the enchantment to various helmets, but it doesn't work. The anvil doesn't seem to consider the enchantment compatible.

**Comment by Nuchaz** [comment]
I'll look into this. When you apply reading to a helmet, the helmet should act just like the reading glasses, but I just tested and that isn't happening like it should.

**Comment by Nuchaz** [comment]
I found and fixed the problem, expect helmets with the reading enchantment to function like the reading glasses again in v2.4.5

**Comment by Nuchaz** [comment]
I just released v2.4.5 of BiblioCraft which has fixed this issue.

**Comment by psychofad** [comment]
I see this issue is supposed to be fixed, but unfortunately, it still seems to be somehow messed up.  For one, the crafting recipe, any enchanted book + glasses = Reading Enchant book, no longer exists.  Additionally, the book still cannot be applied to any helmet, the server operator on the server I played on tried to do so via command and was unable to get that to work either, so it still seems like it is being blocked as if we were attempting to put it on our boots for example.

This is what I see if I look up the books uses (press U in JEI):
![image](https://user-images.githubusercontent.com/1578429/44182164-b335ef00-a0d3-11e8-97c3-f95b7e14f6ab.png)

**Comment by psychofad** [comment]
should I open a new issue for this or is there some new book helmet that I have missed out on?
:D

**Comment by psychofad** [comment]
figured it might be easier for you to track this way

**Comment by Shibva** [comment]
hello I think I found the issue, It does not seem to like being enchanted when other enchanted items are pressent

**Comment by Shibva** [comment]
I was able to enchnt it using an enchanrtment applicator
![image](https://user-images.githubusercontent.com/38770780/74895219-18b90a80-535f-11ea-8ee3-874ff498f1b1.png)

**Comment by Shibva** [comment]
It wont work if other enchantments are one it but once its on their, the applicator wont work, however can be used with an anvil
